### ISSUE TITLE
Required 1.0.16 with ability to setup timeout.

### ISSUE THREAD

**Issue by vik-buchinski-azati** [ButterCMS/buttercms-js#1]
Hi, I've just started integration of buttercms on React, and I have specific case, when i must increase request time, but version 1.0.16 still not in production. So my question is when version 1.0.16 will be in production? (on npmjs?)

**Comment by rogerjin12** [comment]
Hey @vik-buchinski-azati thanks for the note. We just published 1.0.16 to prod:  https://unpkg.com/buttercms@1.0.16/dist/butter.min.js

Give it a try and let us know if you have any issues. Thanks again!

**Comment by rogerjin12** [comment]
And of course, this is also updated on NPM as well.
