### ISSUE TITLE
Can no longer import Butter in a NextJS project

### ISSUE THREAD

**Issue by jontewks** [ButterCMS/buttercms-js#105]
Hello! 2.1.2 was the last version of butter that is working for us, I believe the issue arose in https://github.com/ButterCMS/buttercms-js/commit/18731dda664d54e3be07bfc65fc195125b554c83

Now with the latest version of buttercms I get the following error from previously working code: `Attempted import error: 'buttercms' does not contain a default export (imported as 'Butter').`

This is with
buttercms: 2.1.4
next: 14.2.12
node: 20.17.0

**Comment by notafunction** [comment]
I've found that importing the Butter function directly from 'lib' resolves this:

`import Butter from 'buttercms/lib/butter`

**Comment by courcelan** [comment]
Thank you Matt! We are looking into the issue and hope to have a more straight forward fix soon.

**Comment by ViolanteCodes** [comment]
@jontewks @notafunction 

This should be fixed with `2.2.0`, thank you.
