### ISSUE TITLE
Typescript build error in butter.d.ts

### ISSUE THREAD

**Issue by Jacob-Bass** [ButterCMS/buttercms-js#16]
butter.d.ts is throwing an error when I try to build my project using typescript. 

```
declare module "buttercms" {

  export = Butter;  <-- This line throwing error

}
```

`Error: "Exports and export assignments are not permitted in module augmentations."`

**Comment by jakelumetta** [comment]
Thanks @Jacob-Bass - will take a look at this.

**Comment by jakelumetta** [comment]
@jkelin Can you confirm you run into the same issue when using typescript?  I believe this line may be causing some issues:  https://github.com/ButterCMS/buttercms-js/commit/e470ba875d2416c5a8d7b36bce4c5d0de5fe60a5#diff-7af3c5bb3871283c4aedd61de987d242R1

**Comment by jkelin** [comment]
My apologies. I can confirm that this has been triggered by my change. I am not sure how this could have slipped through my initial testing.

**Comment by jakelumetta** [comment]
Thanks @jkelin !  @Jacob-Bass  we've deployed this updated version. Can you confirm it fixes your issue?
