### ISSUE TITLE
TypeError wrapping returned promise to observable

### ISSUE THREAD

**Issue by chan1ks** [ButterCMS/buttercms-js#19]
Hi running into an issue with the latest version (1.2.2) typings.
In 1.1.4, I was able to wrap the Promise return in an observable `from()` for an Angular Injectable, but now I get the following:

![image](https://user-images.githubusercontent.com/9042219/75218137-8f3a7b80-5756-11ea-8c06-8dd54354a25f.png)

This error occurs just after a successful returned API response. Rxjs maps the value from the service then errors just after the observable's completion.

After some experimenting, comparing 1.1.4 and 1.2.2, the only real difference I see are the type definitions significantly changed.

The client package is pretty handy, but this lies outside the scope of Angular's context.

**Comment by chan1ks** [comment]
Finally figured it out. There's an issue with my service wrapper.

**Comment by jakelumetta** [comment]
Ok thanks for letting us know @chan1ks
