### ISSUE TITLE
No errors returned, when request failed by timeout

### ISSUE THREAD

**Issue by vik-buchinski-azati** [ButterCMS/buttercms-js#2]

**Comment by rogerjin12** [comment]
Per #1 , can you give that a try let me know if that resolves this issue?

**Comment by vik-buchinski-azati** [comment]
@rogerjin12 I tested, and I see, that this case still doesn't work.
my code:
`    this.butter.post.list({ page: pageNumber, page_size: pageSize }).then(
      (response) => {
        clearTimeout(this.butterErrorTimeout); // timeout bugfix
        let newState = {};

        if (response.status === 200) {
          newState = {
            posts: response.data.data,
            pagination: response.data.meta,
            currentPage: pageNumber,
          };
        }

        newState = {
          ...newState,
          loading: false,
        };

        this.setState(newState);
      }
    );`

So, how i see, that it should work: 
1. Fetch posts
2. Request cancelled by timeout
3. .then callback called with appropriate status and statusMessage (but on this step nothing called or returned)

**Comment by rogerjin12** [comment]
@vik-buchinski-azati Thanks for the additional detail. This is on our roadmap to address. In the meantime you can set your timeout to a higher value to avoid having to put custom error handling around this.

Also, if you're interested in submitting a patch feel free to give it a shot and we'll send you a gift 😄

**Comment by rogerjin12** [comment]
@vik-buchinski-azati Hi Victor. I investigated this and an error is returned. You need to catch it as part of the promise callback chain. Try this:

```javascript
var butter = require('./lib/butter')('your api token', true, 1);

butter.post.list({page: 1, page_size: 10})
  .then(function(response) {
    console.log(response.data)
  }).catch(function(response) {
    console.log('this is an error', response)
  });
```
