### ISSUE TITLE
Pages list always returns an empty array

### ISSUE THREAD

**Issue by BaseCrusher** [ButterCMS/buttercms-js#47]
When calling: `https://api.buttercms.com/v2/pages/*/?preview=1&auth_token=<api_key>` according to the API doc it should return  me an array with all available pages.
But the array is always empty even though we have data and using queuing it like this works:  
`https://api.buttercms.com/v2/pages/<page_type>/<page_key>/?auth_token=<api_key>`

**Comment by ViolanteCodes** [comment]
@BaseCrusher Sorry, didn't see this! I'm sorry to hear that you're having some trouble with the API - can you possibly contact us via the chat on our website? We can take a look and see if we can't help, but we'd need some more info from you :)

Thanks!
