### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by jackdomleo7** [ButterCMS/buttercms-js#49]
Is there a maintained changelog for this package anywhere, I can't seem to find one? It's important for developers to be aware of any changes in packages between versions

**Comment by ViolanteCodes** [comment]
@jackdomleo7 we've merged in a changelog for the most recent changes, and we are reviewing another PR that will hopefully get this all sorted out. Thank you for your patience as we got this figured out :)

**Comment by prokopsimek** [comment]
@ViolanteCodes Changelog has already been created. I suggest closing this issue.

**Comment by ViolanteCodes** [comment]
@prokopsimek yep, acknowledged, closing.
