### ISSUE TITLE
missing git tags

### ISSUE THREAD

**Issue by irnnr** [ButterCMS/buttercms-js#51]
Please push your git tags. I see there's been a new patch version release of the package to npm, v1.2.10. It seems to break our integration, likely related to updating axios. I went back to v1.2.9 which works, but I can't find the according git tags for these releases here. So it's hard to investigate what caused the break.

**Comment by prokopsimek** [comment]
@ViolanteCodes Tags are already created and will be in the future. https://github.com/ButterCMS/buttercms-js/tags I suggest closing this issue.

**Comment by ViolanteCodes** [comment]
@prokopsimek acknowledged, closing this issue (cc @irnnr  - tags should be autogenerating with package updates and pushing to both git and npmjs)
