### ISSUE TITLE
NPM community repository is missing version 1.2.11

### ISSUE THREAD

**Issue by ariveron** [ButterCMS/buttercms-js#59]
The latest version `buttercms` on [NPM](https://www.npmjs.com/package/buttercms/?activeTab=versions) is 1.2.10, when will version 1.2.11 be published to NPM so that we can get the fix for the [axios.create bug](https://github.com/ButterCMS/buttercms-js/pull/57)?

**Comment by courcelan** [comment]
@ariveron we have published 1.2.11 to NPM.

Thank you!

**Comment by ariveron** [comment]
@courcelan thank you!
