### ISSUE TITLE
my params are being converted

### ISSUE THREAD

**Issue by kondasoft** [ButterCMS/buttercms-js#7]
Hi,

im writting this:

`butter.page.list('support_faq', ['&order=-date_published'])`

but is being converted to this

`GET https://api.buttercms.com/v2/pages/support_faq/?0=%26order%3D-date_published 401 (Unauthorized)`

why not making optional params to object instead of arrays?

**Comment by jakelumetta** [comment]
`params` should a dictionary

`butter.page.list('support_faq', { order: '-date_published'} )`

**Comment by jakelumetta** [comment]
Check the README for more examples: https://github.com/ButterCMS/buttercms-js#pages

**Comment by kondasoft** [comment]
Ok thanks i must have been tired. One thing is to update the docs especially 
https://buttercms.com/docs/api-client/vuejs
and the
https://buttercms.com/docs/api/#pages
there is no clear way to demonstrate how to use optional params

**Comment by jakelumetta** [comment]
Good suggestion!  Thanks
