### ISSUE TITLE
how cancel request when get post list 

### ISSUE THREAD

**Issue by uxitten** [ButterCMS/buttercms-js#8]
i want cancel request when component componentWillUnmount

**Comment by jakelumetta** [comment]
Hi! Why is it important to cancel the request?

**Comment by uxitten** [comment]
Because I do not want to do extra work

**Comment by uxitten** [comment]
like `abort` method in ajax

**Comment by jakelumetta** [comment]
I mean, what happens if the requests continues / completes. What is the practical impact to your application?  Can you provide more details around the real-world use case for this?

**Comment by uxitten** [comment]
https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html
