### ISSUE TITLE
await butter.page.retrieve doesn't provide error status code on Error

### ISSUE THREAD

**Issue by AlyonaSidarenka** [ButterCMS/buttercms-js#93]
when making `butter.page.retrieve` it is expected that `error` will have status code.

```
const fn = async () => {
  try {
    await butter.page.retrieve(type, slug, params);
  } catch (error) {}
```
Actual result: `error` type is string which is error message
Expected result: `error.response.status` is defined

**Comment by courcelan** [comment]
Hello @AlyonaSidarenka, please take a look at the PR issued #94 and see if this meets your needs.

Thank you!

**Comment by ViolanteCodes** [comment]
@AlyonaSidarenka This fix has been merged in :)
