### ISSUE TITLE
Please add V2 API typings to package

### ISSUE THREAD

**Issue by hjrdave** [ButterCMS/buttercms-js#97]
It seems that the typings are still V1. This makes it difficult to implement this with out newer API typings.

**Comment by ViolanteCodes** [comment]
@hjrdave thank you for pointing this out - we've pinged this issue over to one of our JS devs. I will update you as soon as we have a resolution.

**Comment by jessupjs** [comment]
Hi! I am just now trialing and am having similar issues:

` Error: export 'default' (imported as 'Butter') was not found in 'buttercms' (module has no exports)`

Is this issue scheduled (I see now it was originally posted > 1mo ago)?

Tks!
